include "oxygen_sensor.h"

/* Static Look-Up Table generated by the NJIT Python Engine */
/* Maps 10-bit ADC (shifted to 8-bit index 0-255) to O2 percentages */
constexpr float O2_LOOKUP_TABLE[256] = {
    0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f,
    0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f,
    0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f,
    0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f,
    0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f,
    0.00f, 0.00f, 0.00f, 0.00f, 0.32f, 0.94f, 1.57f, 2.19f,
    2.81f, 3.43f, 4.05f, 4.67f, 5.29f, 5.91f, 6.53f, 7.15f,
    7.77f, 8.39f, 9.01f, 9.63f, 10.25f, 10.88f, 11.50f, 12.12f,
    12.74f, 13.36f, 13.98f, 14.60f, 15.22f, 15.84f, 16.46f, 17.08f,
    17.70f, 18.32f, 18.94f, 19.56f, 20.18f, 20.81f, 21.43f, 22.05f,
    22.67f, 23.29f, 23.91f, 24.53f, 25.15f, 25.77f, 26.39f, 27.01f,
    27.63f, 28.25f, 28.87f, 29.49f, 30.12f, 30.74f, 31.36f, 31.98f,
    32.60f, 33.22f, 33.84f, 34.46f, 35.08f, 35.70f, 36.32f, 36.94f,
    37.56f, 38.18f, 38.80f, 39.42f, 40.05f, 40.67f, 41.29f, 41.91f,
    42.53f, 43.15f, 43.77f, 44.39f, 45.01f, 45.63f, 46.25f, 46.87f,
    47.49f, 48.11f, 48.73f, 49.36f, 49.98f, 50.60f, 51.22f, 51.84f,
    52.46f, 53.08f, 53.70f, 54.32f, 54.94f, 55.56f, 56.18f, 56.80f,
    57.42f, 58.04f, 58.66f, 59.29f, 59.91f, 60.53f, 61.15f, 61.77f,
    62.39f, 63.01f, 63.63f, 64.25f, 64.87f, 65.49f, 66.11f, 66.73f,
    67.35f, 67.97f, 68.60f, 69.22f, 69.84f, 70.46f, 71.08f, 71.70f,
    72.32f, 72.94f, 73.56f, 74.18f, 74.80f, 75.42f, 76.04f, 76.66f,
    77.28f, 77.91f, 78.53f, 79.15f, 79.77f, 80.39f, 81.01f, 81.63f,
    82.25f, 82.87f, 83.49f, 84.11f, 84.73f, 85.35f, 85.97f, 86.59f,
    87.21f, 87.84f, 88.46f, 89.08f, 89.70f, 90.32f, 90.94f, 91.56f,
    92.18f, 92.80f, 93.42f, 94.04f, 94.66f, 95.28f, 95.90f, 96.52f,
    97.15f, 97.77f, 98.39f, 99.01f, 99.63f, 100.00f, 100.00f, 100.00f,
    100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f,
    100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f,
    100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f,
    100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f,
    100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f,
    100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f, 100.00f
};

uint16_t nativeAnalogRead(uint8_t pin) {
    (void)pin;
    return 842; /* Simulated healthy ADC read */
}

bool readOxygenLevel(float& o2Percentage) {
    uint16_t rawAdcValue = nativeAnalogRead(PIN_O2_ADC);

    /* Single-cycle bitwise shift replaces heavy floating-point division math */
    uint16_t lutIndex = rawAdcValue >> 2;

    if (lutIndex > 255) {
        lutIndex = 255;
    }

    o2Percentage = O2_LOOKUP_TABLE[lutIndex];

    /* Guard clause instantly traps severed wire voltages (Live-Zero fault) */
    if (o2Percentage <= 0.0f) return false;

    return true;
}
